spring.application.name=hub


# Server Port
server.port=8082

# MySQL Database Config
spring.datasource.url=jdbc:mysql://localhost:3306/tool_hub
spring.datasource.username=root
spring.datasource.password=Deepak@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


# Gmail Settings -----
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=dk88107765@gmail.com
spring.mail.password=

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


razorpay.key.id=
razorpay.key.secret=


openrouter.api.key=
